spring.application.name=tabuleiro-jogo
server.port=${PORT:8080}

spring.thymeleaf.cache=false

# Debug: mostrar detalhes de erros
server.error.include-message=always
server.error.include-stacktrace=always
server.error.include-exception=true
logging.level.org.thymeleaf=DEBUG
logging.level.dev.tabuleiro=DEBUG
